# Generated by Django 3.0.2 on 2020-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200203_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='owner',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
