# Generated by Django 3.0.2 on 2020-03-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
    ]
